{% set name = "performer-pytorch" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/performer-pytorch-{{ version }}.tar.gz
  sha256: 90f29ec0417ff68be4cd1c3d6b4005cc23f60a6ea34d182295b11571dab3d53c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - einops >=0.3
    - local-attention >=1.1.1
    - pytorch >=1.6
    - axial-positional-embedding >=0.1.0

test:
  imports:
    - performer_pytorch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lucidrains/performer-pytorch
  summary: An implementation of Performer, a linear attention-based transformer, in Pytorch
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - maresb
